# Site settings
title: Dev is Awesome!
email: aloisioaw@gmail.com
description: "Minhas anotações sobre desenvolvimento de software e outras coisas."
baseurl: ""
url: "http://aloisioaw.github.io/"
github_username: aloisioaw
linkedin: "http://br.linkedin.com/pub/aloisio-arsego-wohlmeister/21/372/637"
github: "https://github.com/aloisioaw"

# Build settings
markdown: kramdown
permalink: pretty

#Author
authors:
  aloisioaw:
    display_name: Aloisio Arsego Wohlmeister
    about_page: sobre

plugins:
  - jekyll-sitemap